// Export everything from the emulator components package so the frontend can import it
export { BaseComponent } from './BaseComponent';
export { default as openhwLed } from './openhw-led';
export { default as openhwArduinoUno } from './openhw-arduino-uno';
export { default as openhwPico } from './openhw-pico/index.ts';
export { default as openhwPicoW } from './openhw-pico-w/index.ts';
export { default as openhwResistor } from './openhw-resistor';
export { default as openhwPushbutton } from './openhw-pushbutton';
export { default as openhwPowerSupply } from './openhw-power-supply';
export { default as openhwNeopixelMatrix } from './openhw-neopixel-matrix';
export { default as openhwBuzzer } from './openhw-buzzer';
export { default as openhwMotor } from './openhw-motor';
export { default as openhwServo } from './openhw-servo';
export { default as openhwMotorDriver } from './openhw-motor-driver';
export { default as openhwSlidePotentiometer } from './openhw-slide-potentiometer';
export { default as openhwPotentiometer } from './openhw-potentiometer';
export { default as shiftRegister } from './shift_register';
export { default as openhwMax7219 } from './openhw-max7219';
export { default as openhwSSD1306Oled } from './openhw-ssd1306-oled';
export { default as openhw7Segment } from './openhw-7segment';
export { default as openhwIli9341 } from './openhw-ili9341';
export { default as openhwLcd2004I2C } from './openhw-lcd2004-i2c';
export { default as openhwLcd1602I2C } from './openhw-lcd1602-i2c';
export { default as openhwLcd1602 } from './openhw-lcd1602';
export { default as openhwLdrModule } from './openhw-ldr-module';
export { default as max30102 } from './max30102';
export { default as openhwSdCard } from './openhw-sd-card';
export { default as openhwMembraneKeypad } from './openhw-membrane-keypad';
export { default as openhwAnalogJoystick } from './openhw-analog-joystick';
export { default as openhwTm16377Segment } from './openhw-tm1637-7segment';
export { default as openhwNeopixelRing } from './openhw-neopixel-ring';
export { default as openhwBreadboard } from './openhw-breadboard';
export { default as openhwBreadboardHalf } from './openhw-breadboard-half';
export { default as openhwBreadboardMini } from './openhw-breadboard-mini';
export { default as openhwA4988 } from './openhw-a4988';
export { default as openhwStepperMotor } from './openhw-stepper-motor';
export { default as openhwNLSF595 } from './openhw-nlsf595';
export { default as openhwCD74HC4067 } from './openhw-cd74hc4067';
export { default as openhwL293D } from './openhw-l293d';
export { default as openhwRGBLED } from './openhw-rgb-led';
export { default as openhwRotaryEncoder } from './openhw-rotary-encoder';
export { default as openhwLogicAnalyzer } from './openhw-logic-analyzer';
export { default as openhwNokia5110 } from './openhw-nokia-5110';
export { default as openhwSoilMoistureSensor } from './openhw-soil-moisture-sensor';
export { default as openhwNpnTransistor } from './openhw-npn-transistor';
export { default as openhwDiode } from './openhw-diode';
export { default as openhwPhotodiode } from './openhw-photodiode';
export { default as openhwPCA9685 } from './openhw-pca9685';
export { default as openhwPCA9865 } from './openhw-pca9865';
export { default as openhwArduinoSensorShield } from './openhw-arduino-sensor-shield';
export { default as openhwArduinoNano } from './openhw-arduino-nano';
export { default as openhwBattery } from './openhw-battery';
export { default as openhwCharger } from './openhw-charger';
export { default as openhwPhotoresistor } from './openhw-photoresistor';
export { default as openhwNtcTemperatureSensor } from './openhw-ntc-temperature-sensor';
export { default as openhwBmp180 } from './openhw-bmp180';
export { default as openhwDs1307Rtc } from './openhw-ds1307-rtc';
export { default as openhwMpu6050 } from './openhw-mpu6050';
export { default as openhwNtcThermistor } from './openhw-ntc-thermistor';
export { default as openhwRelayModule } from './openhw-relay-module';


export { default as logicMux2to1 } from './logic-mux-2to1';
export { default as logicDFlipFlop } from './logic-d-flipflop';
export { default as logicDFlipFlopR } from './logic-d-flipflop-r';
export { default as logicDFlipFlopDsr } from './logic-d-flipflop-dsr';
export { default as logicClockGenerator } from './logic-clock-generator';
export { default as logicIc74xx } from './logic-ic-74xx';
export { default as openhwArduinoMega } from './openhw-arduino-mega';
export { default as openhwAttiny85 } from './openhw-attiny85';
export { default as openhwHcSr04 } from './openhw-hc-sr04';
export { default as openhwSimulationMonitor } from './openhw-simulation-monitor';
export { default as openhwDs18b20 } from './openhw-ds18b20';
export { default as openhwIrReceiver } from './openhw-ir-receiver';
export { default as openhwMfrc522 } from './openhw-mfrc522';

export { FullCircuitValidator, analyzeCodeHardwareSync, ProtocolAnalyzer, runUnifiedValidation } from '../circuit-validation/index.js';


