import torch
from transformers import T5ForConditionalGeneration, T5Tokenizer, Trainer, TrainingArguments, DataCollatorForSeq2Seq
from datasets import load_dataset
import os

# --- 1. Setup Model & Tokenizer ---
MODEL_NAME = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(MODEL_NAME)
model = T5ForConditionalGeneration.from_pretrained(MODEL_NAME)

# --- 2. Load Data ---
# Assumes dataset.jsonl exists (generated by dataset_generator.py)
dataset = load_dataset('json', data_files='dataset.jsonl', split='train')
dataset = dataset.train_test_split(test_size=0.1)

def preprocess_function(examples):
    inputs = ["translate English to CircuitJSON: " + doc for doc in examples["text"]]
    model_inputs = tokenizer(inputs, max_length=128, truncation=True, padding="max_length")
    
    # Target is the string representation of the JSON plan
    labels = tokenizer([str(plan) for plan in examples["plan"]], max_length=256, truncation=True, padding="max_length")
    
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_datasets = dataset.map(preprocess_function, batched=True)

# --- 3. Training Arguments (Optimized for RTX 5050) ---
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=10,
    fp16=True, # Mixed precision for RTX 50 series
    push_to_hub=false,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=DataCollatorForSeq2Seq(tokenizer, model=model)
)

# --- 4. Start Training ---
print("🚀 Starting training on RTX 5050...")
trainer.train()

# --- 5. Export to ONNX ---
# This is the format used by Transformers.js in the browser
print("📦 Exporting to ONNX for browser use...")
# (In a real scenario, you'd use the 'optimum' library for high-quality export)
# For now, we save the PyTorch model; you'll run:
# python -m optimum.exporters.onnx --model results/checkpoint-XXX --task text2text-generation-with-past onnx_output/
model.save_pretrained("./final_model")
tokenizer.save_pretrained("./final_model")

print("✅ Training Complete! Model saved to ./final_model")
